image_tag: future-architecture
solr_replicas:
  - name: remote-site
    master_url: https://esgf-fedtest.llnl.gov/solr
    poll_interval: "06:00:00"

wget_api_image_prefix: muryanto1
wget_api_image_tag: "1.0"
wget_api_image_pull: "{{ image_pull }}"
wget_api_image_repository: "esgf-wget"

wget_api:
  debug: False
  secret_key: "&5aq3uq6t8j2y)e2ul@*7jd20=iqp)u141@@7#zu3o3zup_fh+"
  allowed_hosts: "*"
  solr_url: "https://esgf-node.llnl.gov/solr"
  solr_shards:
    - localhost:8983/solr
    - localhost:8985/solr
    - localhost:8987/solr
    - localhost:8988/solr
    - localhost:8990/solr
    - localhost:8993/solr
    - localhost:8994/solr
    - localhost:8995/solr
    - localhost:8996/solr
    - localhost:8997/solr
  allowed_projects_json: "esgf_wgetapi_allowed_projects.json"
  allowed_projects:
    - "CMIP6"
    - "CMIP5"
  script_file_default_limit: 500
  script_file_max_limit: 50000
  max_dir_length: 50
  data_upload_max_number_fields: 10240
  config_path: "/esg/config"
  config: "esgf_wget_config"
